In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [2]:
import numpy

In [4]:
n=numpy.arange(27)

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
m=numpy.asarray([[123,12,123,12,33],[],[]], dtype=object)
type(m)

numpy.ndarray

In [11]:
import cv2

In [17]:
im_g=cv2.imread("../../images/smallgray.png",1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [19]:
cv2.imwrite("../../images/newsmallgray.png",im_g)

True

In [38]:
im_g=cv2.imread("../../images/smallgray.png",0)

In [35]:
im_g[1,2:4]

array([255, 255], dtype=uint8)

In [40]:
for i in im_g:
    print(i)
  

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [41]:
for i in im_g.flat:
    print(i)  

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
